---
# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image: gitpod/workspace-full

additionalRepositories:
  - url: https://github.com/tkhieu/gitpod-starter
    checkoutLocation: gp-df

tasks:
  - name: setup dotfiles
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
        cd ../gp-df
    init: |
        ./brew.sh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    command: |
        echo "Finish setup dotfiles"

  - init: |
      echo "Hello Gitpod"
      
      
      

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
    - "graphql.vscode-graphql-syntax"